import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  // next-env.d.ts is generated by Next on every build and uses a triple-slash
  // reference, which next/typescript itself flags as an error. Linting a file
  // the framework rewrites is pointless — and it fails the build.
  { ignores: ["next-env.d.ts", ".next/**", ".remember/**", ".backups/**"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default eslintConfig;
